#!/bin/bash
set -e

# remove the default database, will create from init
rm -rf /var/lib/postgresql/$POSTGRESQL_VERSION/main

# copy custom configs
rm -f /etc/postgresql/$POSTGRESQL_VERSION/main/postgresql.conf && cp /app/setup/postgresql.conf /etc/postgresql/$POSTGRESQL_VERSION/main/postgresql.conf
rm -f /etc/postgresql/$POSTGRESQL_VERSION/main/pg_hba.conf && cp /app/setup/pg_hba.conf /etc/postgresql/$POSTGRESQL_VERSION/main/pg_hba.conf

echo ""
echo "*************************************************************************"
echo "* Please login to postgresql and create the required database and       *"
echo "* database user with remote login access so that other containers can   *"
echo "* use it.                                                               *"
echo "*                                                                       *"
echo "* e.g.                                                                  *"
echo "*   sudo -u postgres createuser db_user                                 *"
echo "*   sudo -u postgres psql                                               *"
echo "*   > \password db_user                                                 *"
echo "*   sudo -u postgres createdb -O db_user db_name                        *"
echo "*************************************************************************"
echo ""
