#!/bin/bash

# Fail hard and fast
set -eo pipefail

# etcd and key prefixes
ETCD=${ETCD:-172.17.42.1:4001}
ETCD_KEYS_PREFIX=${ETCD_KEYS_PREFIX:-/ci/databases/stash}

# generate a password for root.
ROOT_PASSWORD=$(pwgen -c -n -1 12)
echo "root:$ROOT_PASSWORD" | chpasswd
echo User: root Password: $ROOT_PASSWORD

if [ ! -z "$SSH_AUTHORIZED_KEYS" ]; then
  echo "Starting sshd..."
  /usr/bin/supervisord
  supervisorctl start sshd
  ssh-authorized-keys $SSH_AUTHORIZED_KEYS
fi

# generate toml file
cat >> /etc/confd/conf.d/stash.toml <<EOF
[template]
keys = [
  "$ETCD_KEYS_PREFIX/driver",
  "$ETCD_KEYS_PREFIX/url",
  "$ETCD_KEYS_PREFIX/username",
  "$ETCD_KEYS_PREFIX/password"
]
owner       = "stash"
group       = "stash"
mode        = "0644"
src         = "stash-config.properties.tmpl"
dest        = "$STASH_HOME/stash-config.properties"
EOF

appStart () {
    # fix permissions
    chown stash:stash $STASH_HOME
    chown -R stash:stash /opt/atlassian-stash*

    # copy template file
    chown stash:stash /etc/confd/conf.d/stash.toml
    cp -p $STASH_HOME/stash-config.properties.tmpl /etc/confd/templates/stash-config.properties.tmpl

    # Loop until confd has updated the stash config
    until confd -onetime -backend etcd -node $ETCD -config-file /etc/confd/conf.d/stash.toml; do
      echo "Waiting for confd to refresh stash-config.properties"
      sleep 5
    done

    # Start Atlassian in the foreground
    sudo -u stash STASH_HOME=$STASH_HOME /opt/atlassian-stash/bin/start-stash.sh -fg
}

appHelp () {
    echo "Available options:"
    echo " app:start                - Start the mysql server and watch the log (default)"
    echo " app:help                 - Displays the help"
    echo " [command]                - Execute the specified linux command eg. bash."
}

case "$1" in
    app:start)
        appStart
        ;;
    app:help)
        appHelp
        ;;
    *)
        if [ -x $1 ]; then
            $1
        else
            prog=$(which $1)
            if [ -n "${prog}" ] ; then
                shift 1
                $prog $@
            else
                appHelp
            fi
        fi
        ;;
esac

exit 0
