#!/bin/bash
set -e

# remove the default database, will create from init. Also, 
# conf.d files should be removed, my.cnf is enough.
rm -Rf /etc/mysql/conf.d/*
rm -Rf /var/lib/mysql/*

# copy custom my.cnf
rm -f /etc/mysql/my.cnf && cp /app/setup/my.cnf /etc/mysql/my.cnf

echo ""
echo "*************************************************************************"
echo "* Please login to the mysql server and create the required database and *"
echo "* database user with remote login access so that other containers can   *"
echo "* use it.                                                               *"
echo "*                                                                       *"
echo "* e.g.                                                                  *"
echo "*   CREATE DATABASE db_name;                                            *"
echo "*   CREATE USER 'db_user'@'%' IDENTIFIED BY 'db_password';              *"
echo "*   GRANT ALL ON DATABASE.* to 'db_user'@'%';                           *"
echo "*   FLUSH PRIVILEGES;                                                   *"
echo "*************************************************************************"
echo ""
