#!/bin/bash

# exit on errors
set -e

usage() {
  echo "Usage: ./build-and-push.sh base:12.04 ./path-to-dockerfile [ localhost:5000 ]"
  exit 1
}

# binaries
CUT=/usr/bin/cut
DOCKER=/usr/bin/docker

# first parameter is the image name, and as a second parameter an optional repo uri
IMAGE_AND_TAG="$1"
PATH="$2"
REPOSITORY="$3"

# exit if var name is empty
[[ -z "$IMAGE_AND_TAG" ]] && usage;
[[ -z "$PATH" ]] && usage;
[[ -z "$REPOSITORY" ]] && REPOSITORY="localhost:5000";

# split if needed!
IMAGE=$(echo $IMAGE_AND_TAG | $CUT -f1 -d:)
TAG=$(echo $IMAGE_AND_TAG | $CUT -f2 -d:)

# exit if image is empty and set default value for tag (latest)
[[ -z "$IMAGE" ]] && exit 1;
[[ -z "$TAG" ]] && TAG="latest";

# build and tag
$DOCKER build -t glerchundi/$IMAGE:$TAG $PATH/
$DOCKER tag glerchundi/$IMAGE:$TAG $REPOSITORY/glerchundi/$IMAGE:$TAG

# push and remove image pointing to our custom private repository
$DOCKER push $REPOSITORY/glerchundi/$IMAGE
$DOCKER rmi $REPOSITORY/glerchundi/$IMAGE:$TAG