[template]
owner      = "nginx"
group      = "nginx"
mode       = "0644"
src        = "nginx.conf.tmpl"
dest       = "/etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/service nginx reload"
keys       = [
  "$PREFIX"
]